apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-hello-v1
  namespace: kuard
  labels:
    app: hello-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-app
      version: v1.0.0
  template:
    metadata:
      labels:
        app: hello-app
        version: v1.0.0
    spec:
      containers:
      - name: dummy-hello-v1
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080