apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: kuard
  labels:
    app: hello-app
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080